### ISSUE TITLE
java.lang.NoClassDefFoundError: cats/FunctorFilter

### ISSUE THREAD

**Issue by eperinan** [frees-io/sbt-frees-protogen#12]
I am creating a project from https://github.com/frees-io/freestyle-template.g8 and adding the follow plugins, I am getting the following error.

```
resolvers += Resolver.sonatypeRepo("releases")
resolvers += Resolver.bintrayRepo("beyondthelines", "maven")

addSbtPlugin("io.frees" % "sbt-freestyle" % "0.3.6")
addSbtPlugin("io.frees" % "sbt-frees-protogen" % "0.0.10")
```

```
info] Loading settings from build.sbt,version.sbt ...
[error] java.lang.NoClassDefFoundError: cats/FunctorFilter
[error]         at sbtorgpolicies.settings.DefaultSettings.$anonfun$orgCommonDefaultSettings$4(DefaultSettings.scala:74)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: cats.FunctorFilter
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at sbtorgpolicies.settings.DefaultSettings.$anonfun$orgCommonDefaultSettings$4(DefaultSettings.scala:74)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NoClassDefFoundError: cats/FunctorFilter
```

In the release 0.0.8 works fine but after generate the release 0.0.9 I am getting this error.

This is the PR where probably we can start to debug something https://github.com/frees-io/sbt-freestyle-protogen/pull/5/files

**Comment by eperinan** [comment]
This issue depends of https://github.com/47deg/sbt-org-policies/issues/655

**Comment by eperinan** [comment]
Please @suhasgaddam, let me know when the dependency for solve this issue will be solved

**Comment by suhasgaddam** [comment]
@eperinan My local tests and the sbt plugin tests show that 

```
addSbtPlugin("io.frees" % "sbt-freestyle" % "0.3.7")
addSbtPlugin("io.frees" % "sbt-frees-protogen" % "0.0.13-SNAPSHOT")
```
work together, and `protoGen` generates the `.proto` files.

**Comment by juanpedromoreno** [comment]
Nice @suhasgaddam , can you check it @eperinan ?

**Comment by eperinan** [comment]
Tomorrow I will take a look and I will check it. Thanks @suhasgaddam.

**Comment by eperinan** [comment]
Checked and works fine. Great job @suhasgaddam 

I just discovered another bug but I am going to report in a new issue #19 .

So, Do we have to release the version 0.0.13 @suhasgaddam @juanpedromoreno ? 

If the answer is yes, I can do it

**Comment by juanpedromoreno** [comment]
Feel free to open a PR to release a new patch version :+1:
